-- Vertex Red -- Re-seed hospitals with Myanmar names
-- Total: 196 hospitals

DELETE FROM public.hospitals;

ALTER TABLE public.hospitals ADD COLUMN IF NOT EXISTS name_mya TEXT;

INSERT INTO public.hospitals (name, name_mya, township, address, lat, lng, verification_status) VALUES
('Eye,Ear,Nose and Throat Hosptital', 'á€™á€»á€€á€ºá€…á€­áŠá€”á€¬á€¸áŠá€”á€¾á€¬á€á€±á€«á€„á€ºá€¸á€”á€¾á€„á€·á€ºá€œá€Šá€ºá€á€»á€±á€¬á€„á€ºá€¸á€›á€±á€¬á€‚á€«á€€á€¯á€†á€±á€¸á€›á€¯á€¶', 'Aungmyaythazan', 'Mandalay, Mandalay District', 21.9869280, 96.0839160, 'APPROVED'),
('Labor Hospital', 'á€¡á€œá€¯á€•á€ºá€žá€™á€¬á€¸á€†á€±á€¸á€›á€¯á€¶', 'Aungmyaythazan', 'Mandalay, Mandalay District', 22.0009420, 96.1085820, 'APPROVED'),
('Traditional Hospital', 'á€á€­á€¯á€„á€ºá€¸á€›á€„á€ºá€¸á€†á€±á€¸á€›á€¯á€¶', 'Aungmyaythazan', 'Mandalay, Mandalay District', 22.0194710, 96.0976510, 'APPROVED'),
('Chanayethazan General Hospital', 'á€™á€”á€¹á€á€œá€±á€¸á€•á€¼á€Šá€ºá€žá€°á€·á€†á€±á€¸á€›á€¯á€¶á€€á€¼á€®á€¸', 'Chanayethazan', 'Mandalay, Mandalay District', 21.9774460, 96.0903780, 'APPROVED'),
('Children Specialist Hospital', 'á€€á€œá€±á€¸á€›á€±á€¬á€‚á€«á€¡á€‘á€°á€¸á€€á€¯á€†á€±á€¸á€›á€¯á€¶á€€á€¼á€®á€¸(á€™á€”á€¹á€á€œá€±á€¸)', 'Chanayethazan', 'Mandalay, Mandalay District', 21.9773580, 96.0913670, 'APPROVED'),
('Central Women Hospital', 'á€—á€Ÿá€­á€¯á€¡á€™á€»á€­á€¯á€¸á€žá€™á€®á€¸á€†á€±á€¸á€›á€¯á€¶', 'Chanayethazan', 'Mandalay, Mandalay District', 21.9751710, 96.1017950, 'APPROVED'),
('Children Specialist Hospital', 'á€€á€œá€±á€¸á€›á€±á€¬á€‚á€«á€¡á€‘á€°á€¸á€€á€¯á€†á€±á€¸á€›á€¯á€¶á€€á€¼á€®á€¸', 'Chanayethazan', 'Mandalay, Mandalay District', 21.9798330, 96.1052220, 'APPROVED'),
('Disease control Hospital', 'á€€á€°á€¸á€…á€€á€ºá€›á€±á€¬á€‚á€«á€€á€¯á€†á€±á€¸á€›á€¯á€¶', 'Chanayethazan', 'Mandalay, Mandalay District', 21.9728480, 96.0580670, 'APPROVED'),
('University hospital', 'á€á€€á€¹á€€á€žá€­á€¯á€œá€ºá€†á€±á€¸á€›á€¯á€¶', 'Mahaaungmyay', 'Mandalay, Mandalay District', 21.9564020, 96.1006020, 'APPROVED'),
('Orthopedic Specialist Hospital', 'á€¡á€›á€­á€¯á€¸á€›á€±á€¬á€‚á€«á€¡á€‘á€°á€¸á€€á€¯á€†á€±á€¸á€›á€¯á€¶á€€á€¼á€®á€¸', 'Chanmyathazi', 'Mandalay, Mandalay District', 21.9432670, 96.1116820, 'APPROVED'),
('(300) Bedded Hospital', 'á€€á€¯á€á€„á€º(áƒá€á€)á€†á€±á€¸á€›á€¯á€¶', 'Chanmyathazi', 'Mandalay, Mandalay District', 21.9474090, 96.1122960, 'APPROVED'),
('Psychiatric Hospital', 'á€…á€­á€á€ºá€€á€»á€”á€ºá€¸á€™á€¬á€›á€±á€¸á€†á€±á€¸á€›á€¯á€¶', 'Amarapura', 'Mandalay, Mandalay District', 21.8710110, 96.1768180, 'APPROVED'),
('Ta Moke Soe Station Hospital', 'á€á€™á€¯á€á€ºá€†á€­á€¯á€¸á€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Amarapura', 'Mandalay, Mandalay District', 21.8527150, 96.1583030, 'APPROVED'),
('Amarapura Township Hospital', 'á€¡á€™á€›á€•á€°á€›á€™á€¼á€­á€¯á€·á€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Amarapura', 'Mandalay, Mandalay District', 21.8976690, 96.0482530, 'APPROVED'),
('Ye lon Kyaw Station Hospital', 'á€›á€²á€œá€½á€”á€ºá€€á€»á€±á€¬á€ºá€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Amarapura', 'Mandalay, Mandalay District', 21.8348940, 96.0008740, 'APPROVED'),
('Ta Lin Gyi Station Hospital', 'á€á€œá€„á€ºá€¸á€€á€¼á€®á€¸á€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Amarapura', 'Mandalay, Mandalay District', 21.8183030, 96.1138980, 'APPROVED'),
('Drug Hospital', 'á€™á€°á€¸á€šá€…á€ºá€†á€±á€¸á€…á€½á€²á€›á€±á€¬á€‚á€«á€€á€¯á€†á€±á€¸á€›á€¯á€¶', 'Mahaaungmyay', 'Mandalay, Mandalay District', 21.9671800, 96.1062900, 'APPROVED'),
('Tuberculosis Hospital', 'á€á€®á€˜á€®á€›á€±á€¬á€‚á€«á€€á€¯á€†á€±á€¸á€›á€¯á€¶', 'Patheingyi', 'Mandalay, Mandalay District', 21.9905200, 96.1524960, 'APPROVED'),
('Patheingyi Township Hospital', 'á€•á€¯á€žá€­á€™á€ºá€€á€¼á€®á€¸á€™á€¼á€­á€¯á€·á€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Patheingyi', 'Mandalay, Mandalay District', 22.0047680, 96.1667990, 'APPROVED'),
('Kyauk Mee Station Hospital', 'á€€á€»á€±á€¬á€€á€ºá€™á€®á€¸á€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Patheingyi', 'Mandalay, Mandalay District', 21.9053560, 96.1828700, 'APPROVED'),
('Technology University Hospital', 'á€”á€Šá€ºá€¸á€•á€Šá€¬á€á€€á€¹á€€á€žá€­á€¯á€œá€ºá€†á€±á€¸á€›á€¯á€¶', 'Patheingyi', 'Mandalay, Mandalay District', 21.9742950, 96.1941720, 'APPROVED'),
('Pyinoolwin General Hospital', 'á€•á€¼á€„á€ºá€¦á€¸á€œá€½á€„á€ºá€•á€¼á€Šá€ºá€žá€°á€·á€†á€±á€¸á€›á€¯á€¶á€€á€¼á€®á€¸', 'Pyinoolwin', 'Mandalay, Pyinoolwin District', 22.0225120, 96.4661410, 'APPROVED'),
('Zee Pin Gyi Station Hospital', 'á€‡á€®á€¸á€•á€„á€ºá€€á€¼á€®á€¸á€†á€±á€¸á€›á€¯á€¶', 'Pyinoolwin', 'Mandalay, Pyinoolwin District', 21.8684870, 96.3157630, 'APPROVED'),
('Wet Wun Station Hospital', 'á€á€€á€ºá€á€¶á€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Pyinoolwin', 'Mandalay, Pyinoolwin District', 22.0939920, 96.5906170, 'APPROVED'),
('Anar Gyi Hospital', 'á€¡á€”á€¬á€€á€¼á€®á€¸á€›á€±á€¬á€‚á€«á€¡á€‘á€°á€¸á€€á€¯á€†á€±á€¸á€›á€¯á€¶', 'Madaya', 'Mandalay, Pyinoolwin District', 22.3323220, 96.1453000, 'APPROVED'),
('Madaya Township Hospital', 'á€™á€á€¹á€á€›á€¬á€™á€¼á€­á€¯á€·á€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Madaya', 'Mandalay, Pyinoolwin District', 22.2105990, 96.1047280, 'APPROVED'),
('Mway Ta Laing Station Hospital', 'á€™á€¼á€½á€±á€á€œá€­á€¯á€„á€ºá€¸á€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Madaya', 'Mandalay, Pyinoolwin District', 22.2715000, 96.0453300, 'APPROVED'),
('Tha Hpan Daunt Station Hospital', 'á€žá€–á€”á€ºá€¸á€’á€±á€«á€€á€ºá€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Madaya', 'Mandalay, Pyinoolwin District', 22.1390430, 96.0381030, 'APPROVED'),
('U-Hmin Station Hospital', 'á€¥á€™á€¾á€„á€ºá€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Madaya', 'Mandalay, Pyinoolwin District', 22.2627000, 96.0304100, 'APPROVED'),
('Se Taw Gyi Station Hospital', 'á€†á€Šá€ºá€á€±á€¬á€ºá€€á€¼á€®á€¸á€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Madaya', 'Mandalay, Pyinoolwin District', 22.3271170, 96.3126180, 'APPROVED'),
('Singu Township Hospital', 'á€…á€¥á€·á€ºá€€á€°á€¸á€™á€¼á€­á€¯á€·á€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Singu', 'Mandalay, Pyinoolwin District', 22.5474440, 95.9942260, 'APPROVED'),
('Htone Gyi Station Hospital', 'á€‘á€¯á€¶á€¸á€€á€¼á€®á€¸á€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Singu', 'Mandalay, Pyinoolwin District', 22.4338580, 96.0254250, 'APPROVED'),
('Kyi Tauk Pauk Station Hospital', 'á€€á€»á€Šá€ºá€á€±á€¬á€€á€ºá€•á€±á€«á€€á€ºá€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Singu', 'Mandalay, Pyinoolwin District', 22.6949060, 96.0146540, 'APPROVED'),
('Hin Thar Ma Station Hospital', 'á€žá€²á€¡á€„á€ºá€¸á€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Singu', 'Mandalay, Pyinoolwin District', 22.3466970, 96.0186650, 'APPROVED'),
('Mogoke Township Hospital', 'á€™á€­á€¯á€¸á€€á€¯á€á€ºá€™á€¼á€­á€¯á€·á€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Mogoke', 'Mandalay, Pyinoolwin District', 22.9185450, 96.4971790, 'APPROVED'),
('Kyat Pyin Station Hospital', 'á€€á€»á€•á€ºá€•á€¼á€„á€ºá€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Mogoke', 'Mandalay, Pyinoolwin District', 22.9050750, 96.4245440, 'APPROVED'),
('Thabeikkyin Township Hospital', 'á€žá€•á€­á€á€ºá€€á€»á€„á€ºá€¸á€™á€¼á€­á€¯á€·á€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Thabeikkyin', 'Mandalay, Pyinoolwin District', 22.8868810, 95.9814760, 'APPROVED'),
('Ta Gaung Station Hospital', 'á€á€€á€±á€¬á€„á€ºá€¸á€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Thabeikkyin', 'Mandalay, Pyinoolwin District', 23.4943650, 96.0091080, 'APPROVED'),
('Twin Nge Station Hospital', 'á€á€½á€„á€ºá€¸á€„á€šá€ºá€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Thabeikkyin', 'Mandalay, Pyinoolwin District', 23.1080050, 96.0231210, 'APPROVED'),
('Kyar Hnyat Station Hospital', 'á€€á€¼á€¬á€Šá€¾á€•á€ºá€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Thabeikkyin', 'Mandalay, Pyinoolwin District', 23.2474070, 96.0028750, 'APPROVED'),
('Kyaukse General Hospital', 'á€€á€»á€±á€¬á€€á€ºá€†á€Šá€ºá€•á€¼á€Šá€ºá€žá€°á€·á€†á€±á€¸á€›á€¯á€¶á€€á€¼á€®á€¸', 'Kyaukse', 'Mandalay, Kyaukse District', 21.6104120, 96.1276580, 'APPROVED'),
('Min Su Station Hospital', 'á€™á€„á€ºá€¸á€…á€¯á€†á€±á€¸á€›á€¯á€¶', 'Kyaukse', 'Mandalay, Kyaukse District', 21.5111360, 96.1299350, 'APPROVED'),
('Than (East) Station Hospital', 'á€žá€¶á€›á€½á€¬á€†á€±á€¸á€›á€¯á€¶', 'Kyaukse', 'Mandalay, Kyaukse District', 21.4859660, 96.2735720, 'APPROVED'),
('Hpyauk Seik Pin Station Hospital', 'á€–á€»á€±á€¬á€€á€ºá€†á€­á€•á€º(á€…á€€á€ºá€›á€¯á€¶á€…á€¯á€”á€šá€ºá€™á€¼á€±)á€†á€±á€¸á€›á€¯á€¶', 'Kyaukse', 'Mandalay, Kyaukse District', 21.5959860, 96.2706290, 'APPROVED'),
('Sa Mar Station Hospital', 'á€…á€™á€¬á€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Kyaukse', 'Mandalay, Kyaukse District', 21.5596230, 96.0591230, 'APPROVED'),
('Sintgaing Township Hospital', 'á€…á€¥á€·á€ºá€€á€­á€¯á€„á€ºá€™á€¼á€­á€¯á€·á€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Sintgaing', 'Mandalay, Kyaukse District', 21.7387030, 96.0951330, 'APPROVED'),
('Sin Kine Eye Special Hospital', 'á€…á€¥á€·á€ºá€€á€­á€¯á€„á€ºá€™á€»á€€á€ºá€…á€­á€›á€±á€¬á€‚á€«á€¡á€‘á€°á€¸á€€á€¯á€†á€±á€¸á€›á€¯á€¶', 'Sintgaing', 'Mandalay, Kyaukse District', 21.7372670, 96.1072170, 'APPROVED'),
('Pa Leik Station Hospital', 'á€•á€¯á€œá€­á€•á€ºá€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Sintgaing', 'Mandalay, Kyaukse District', 21.8183410, 96.0507850, 'APPROVED'),
('Myittha Township Hospital', 'á€™á€¼á€…á€ºá€žá€¬á€¸á€™á€¼á€­á€¯á€·á€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Myittha', 'Mandalay, Kyaukse District', 21.4225860, 96.1292720, 'APPROVED'),
('Maing Maw Station Hospital', 'á€™á€­á€¯á€„á€ºá€¸á€™á€±á€¬á€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Myittha', 'Mandalay, Kyaukse District', 21.3064950, 96.2148970, 'APPROVED'),
('Ku Me Station Hospital', 'á€€á€°á€™á€²á€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Myittha', 'Mandalay, Kyaukse District', 21.3567810, 96.1540130, 'APPROVED'),
('Ywar Khaing Gyi Station Hospital', 'á€›á€½á€¬á€á€­á€¯á€„á€ºá€€á€¼á€®á€¸á€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Myittha', 'Mandalay, Kyaukse District', 21.3549370, 96.2511290, 'APPROVED'),
('Min Wun Station Hospital', 'á€™á€„á€ºá€¸á€á€”á€º', 'Myittha', 'Mandalay, Kyaukse District', 21.4931090, 96.0196500, 'APPROVED'),
('Gway Station Hospital', 'á€‚á€½á€±á€·á€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Myittha', 'Mandalay, Kyaukse District', 21.4963000, 96.0250300, 'APPROVED'),
('Tada-U Township Hospital', 'á€á€¶á€á€¬á€¸á€¦á€¸á€™á€¼á€­á€¯á€·á€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Tada-U', 'Mandalay, Kyaukse District', 21.8166420, 95.9673640, 'APPROVED'),
('Thein Ni Kan Station Hospital', 'á€žá€­á€”á€¹á€’á€®á€€á€”á€ºá€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Tada-U', 'Mandalay, Kyaukse District', 21.5811800, 95.9079250, 'APPROVED'),
('Taung Pyone Station Hospital', 'á€á€±á€¬á€„á€ºá€•á€¼á€¯á€¶á€¸á€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Tada-U', 'Mandalay, Kyaukse District', 21.7190477, 95.8375861, 'APPROVED'),
('Nyaung Wun Station Hospital', 'á€Šá€±á€¬á€„á€ºá€á€”á€ºá€¸á€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Tada-U', 'Mandalay, Kyaukse District', 21.4917860, 95.9678580, 'APPROVED'),
('Myingyan General Hospital', 'á€™á€¼á€„á€ºá€¸á€á€¼á€¶á€•á€¼á€Šá€ºá€žá€°á€·á€†á€±á€¸á€›á€¯á€¶', 'Myingyan', 'Mandalay, Myingyan District', 21.4747980, 95.3893430, 'APPROVED'),
('San Myeik Khone Station Hospital', 'á€†á€¶á€™á€¼á€­á€á€ºá€á€¯á€¶á€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Myingyan', 'Mandalay, Myingyan District', 21.7347380, 95.4243880, 'APPROVED'),
('Hta Naung Taing Station Hospital', 'á€‘á€”á€±á€¬á€„á€ºá€¸á€á€­á€¯á€„á€ºá€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Myingyan', 'Mandalay, Myingyan District', 21.3974890, 95.3104360, 'APPROVED'),
('Yon Htoe Station Hospital', 'á€šá€¯á€¶á€á€­á€¯á€¸á€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Myingyan', 'Mandalay, Myingyan District', 21.5410270, 95.5352510, 'APPROVED'),
('Taungtha Township Hospital', 'á€á€±á€¬á€„á€ºá€žá€¬á€™á€¼á€­á€¯á€·á€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Taungtha', 'Mandalay, Myingyan District', 21.2681680, 95.4493080, 'APPROVED'),
('Wea Laung Station Hospital', 'á€á€²á€œá€±á€¬á€„á€ºá€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Taungtha', 'Mandalay, Myingyan District', 21.1508750, 95.3755570, 'APPROVED'),
('Kyaw Zi Station Hospital', 'á€€á€»á€±á€¬á€ºá€‡á€®á€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Taungtha', 'Mandalay, Myingyan District', 21.3170680, 95.1821400, 'APPROVED'),
('Za Gyan Station Hospital', 'á€‡á€‚á€»á€™á€ºá€¸á€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Taungtha', 'Mandalay, Myingyan District', 21.2617050, 95.3064930, 'APPROVED'),
('Yone Si Gyi Station Hospital', 'á€›á€¯á€¶á€¸á€…á€Šá€ºá€€á€¼á€®á€¸á€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Taungtha', 'Mandalay, Myingyan District', 21.1957120, 95.5842310, 'APPROVED'),
('Natogyi Township Hospital', 'á€”á€½á€¬á€¸á€‘á€­á€¯á€¸á€€á€¼á€®á€¸á€™á€¼á€­á€¯á€·á€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Natogyi', 'Mandalay, Myingyan District', 21.4253790, 95.6494410, 'APPROVED'),
('Thu Soe Station Hospital', 'á€á€¶á€‡á€­á€¯á€¸á€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Natogyi', 'Mandalay, Myingyan District', 21.3877670, 95.5047630, 'APPROVED'),
('Wet Lu Station Hospital', 'á€á€€á€ºá€œá€°á€¸á€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Natogyi', 'Mandalay, Myingyan District', 21.5305090, 95.7358340, 'APPROVED'),
('Ka Nar Station Hospital', 'á€€á€”á€ºá€”á€¬á€¸á€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Natogyi', 'Mandalay, Myingyan District', 21.4612340, 95.8699260, 'APPROVED'),
('Kyaukpadaung Township Hospital', 'á€€á€»á€±á€¬á€€á€ºá€•á€”á€ºá€¸á€á€±á€¬á€„á€ºá€¸á€™á€¼á€­á€¯á€·á€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Kyaukpadaung', 'Mandalay, Nyaung-U District', 20.8344910, 95.1204850, 'APPROVED'),
('Pway Kyit Station Hospital', 'á€•á€½á€±á€¸á€€á€»á€…á€ºá€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Kyaukpadaung', 'Mandalay, Nyaung-U District', 20.6501000, 95.1200800, 'APPROVED'),
('Let Pan Pyar Station Hospital', 'á€œá€€á€ºá€•á€¶á€•á€¼á€¬á€¸á€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Kyaukpadaung', 'Mandalay, Nyaung-U District', 20.8165920, 95.3836910, 'APPROVED'),
('Popa Station Hospital', 'á€•á€¯á€•á€¹á€•á€«á€¸á€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Kyaukpadaung', 'Mandalay, Nyaung-U District', 20.9354960, 95.1970200, 'APPROVED'),
('Ngazun Township Hospital', 'á€„á€«á€”á€ºá€¸á€‡á€½á€”á€ºá€™á€¼á€­á€¯á€·á€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Ngazun', 'Mandalay, Myingyan District', 21.8938510, 95.6846770, 'APPROVED'),
('Nga Myar Gyi Station Hospital', 'á€„á€«á€¸á€™á€¼á€¾á€¬á€¸á€€á€¼á€®á€¸á€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Ngazun', 'Mandalay, Myingyan District', 21.7816410, 95.4662430, 'APPROVED'),
('Myo Thar Station Hospital', 'á€™á€¼á€­á€¯á€·á€žá€¬á€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Ngazun', 'Mandalay, Myingyan District', 21.6939540, 95.7184290, 'APPROVED'),
('Nyaung-U General Hospital', 'á€Šá€±á€¬á€„á€ºá€¦á€¸á€•á€¼á€Šá€ºá€žá€°á€·á€†á€±á€¸á€›á€¯á€¶', 'Nyaung-U', 'Mandalay, Nyaung-U District', 21.1839860, 94.9116160, 'APPROVED'),
('Nyaung-U Township Hospital', 'á€„á€«á€·á€žá€›á€±á€¬á€€á€ºá€™á€¼á€­á€¯á€·á€”á€šá€ºá€á€½á€²á€†á€±á€¸á€›á€¯á€¶', 'Nyaung-U', 'Mandalay, Nyaung-U District', 21.1509260, 95.1344200, 'APPROVED'),
('Bagan Myo Thit Station Hospital', 'á€•á€¯á€‚á€¶á€™á€¼á€­á€¯á€·á€žá€…á€ºá€†á€±á€¸á€›á€¯á€¶', 'Nyaung-U', 'Mandalay, Nyaung-U District', 21.1362220, 94.8566100, 'APPROVED'),
('Taung Zin Station Hospital', 'á€á€±á€¬á€„á€ºá€‡á€„á€ºá€¸á€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Nyaung-U', 'Mandalay, Nyaung-U District', 21.0263450, 95.0150000, 'APPROVED'),
('Sint Ku Station Hospital', 'á€…á€¥á€·á€ºá€€á€°á€¸á€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Nyaung-U', 'Mandalay, Nyaung-U District', 20.9507780, 94.8615090, 'APPROVED'),
('Yamethin General Hospital', 'á€›á€™á€Šá€ºá€¸á€žá€„á€ºá€¸á€•á€¼á€Šá€ºá€žá€°á€·á€†á€±á€¸á€›á€¯á€¶', 'Yamethin', 'Mandalay, Yamethin District', 20.4363320, 96.1358010, 'APPROVED'),
('Thit Son Gyi Station Hospital', 'á€žá€…á€ºá€†á€¯á€¶á€€á€¼á€®á€¸á€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Yamethin', 'Mandalay, Yamethin District', 20.4581220, 95.8669020, 'APPROVED'),
('Ywar Tan Station Hospital', 'á€›á€½á€¬á€á€”á€ºá€¸á€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Yamethin', 'Mandalay, Yamethin District', 20.4762150, 96.0132740, 'APPROVED'),
('Htee Hlaing Station Hospital', 'á€‘á€®á€¸á€œá€¾á€­á€¯á€„á€ºá€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Yamethin', 'Mandalay, Yamethin District', 20.3683880, 96.2059570, 'APPROVED'),
('Pyar Si Station Hospital', 'á€•á€»á€¬á€¸á€…á€®á€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Yamethin', 'Mandalay, Yamethin District', 20.2846720, 95.9410370, 'APPROVED'),
('Pyawbwe Township Hospital', 'á€•á€»á€±á€¬á€ºá€˜á€½á€šá€ºá€™á€¼á€­á€¯á€·á€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Pyawbwe', 'Mandalay, Yamethin District', 20.6022030, 96.0430060, 'APPROVED'),
('Shwe Nyaung Hpu Station Hospital', 'á€›á€½á€¾á€±á€Šá€±á€¬á€„á€ºá€–á€°á€¸á€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Pyawbwe', 'Mandalay, Yamethin District', 20.5823890, 96.1952240, 'APPROVED'),
('Yin Taw Station Hospital', 'á€šá€„á€ºá€¸á€á€±á€¬á€ºá€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Pyawbwe', 'Mandalay, Yamethin District', 20.7096890, 95.9443460, 'APPROVED'),
('Taung Nyaung Station Hospital', 'á€á€±á€¬á€„á€ºá€Šá€±á€¬á€„á€ºá€€á€¯á€”á€ºá€¸á€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Pyawbwe', 'Mandalay, Yamethin District', 20.5060560, 95.7736130, 'APPROVED'),
('Yan Aung Station Hospital', 'á€›á€”á€ºá€¡á€±á€¬á€„á€ºá€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Pyawbwe', 'Mandalay, Yamethin District', 20.5413360, 95.9690350, 'APPROVED'),
('Anauk Hlyaw Hpyu Kone Station Hospital', 'á€¡á€”á€±á€¬á€€á€ºá€œá€»á€¾á€±á€¬á€ºá€–á€¼á€°á€€á€¯á€”á€ºá€¸á€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Pyawbwe', 'Mandalay, Yamethin District', 20.6794000, 96.1394500, 'APPROVED'),
('Thee Pin Station Hospital', 'á€žá€®á€¸á€•á€„á€ºá€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Pyawbwe', 'Mandalay, Yamethin District', 20.5980510, 95.9489870, 'APPROVED'),
('Traditional Hospital', 'á€á€­á€¯á€„á€ºá€¸á€›á€„á€ºá€¸á€†á€±á€¸á€›á€¯á€¶', 'Pyawbwe', 'Mandalay, Yamethin District', 20.6178730, 96.0386650, 'APPROVED'),
('Meiktila General Hospital', 'á€™á€­á€á€¹á€‘á€®á€œá€¬á€•á€¼á€Šá€ºá€žá€°á€·á€†á€±á€¸á€›á€¯á€¶á€€á€¼á€®á€¸', 'Meiktila', 'Mandalay, Meiktila District', 20.8766240, 95.8447270, 'APPROVED'),
('Shan Ma Nge Station Hospital', 'á€›á€¾á€™á€ºá€¸á€™á€„á€šá€ºá€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Meiktila', 'Mandalay, Meiktila District', 20.8385000, 95.6174200, 'APPROVED'),
('Ah Lel Station Hospital', 'á€¡á€œá€šá€ºá€›á€½á€¬á€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Meiktila', 'Mandalay, Meiktila District', 20.7674900, 95.7732230, 'APPROVED'),
('Mahlaing Township Hospital', 'á€™á€œá€¾á€­á€¯á€„á€ºá€™á€¼á€­á€¯á€·á€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Mahlaing', 'Mandalay, Meiktila District', 21.0979170, 95.6454030, 'APPROVED'),
('Kyauk Tan Station Hospital', 'á€€á€»á€±á€¬á€€á€ºá€á€”á€ºá€¸á€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Mahlaing', 'Mandalay, Meiktila District', 21.0669470, 95.5867060, 'APPROVED'),
('Se To Station Hospital', 'á€†á€Šá€ºá€á€­á€¯á€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Mahlaing', 'Mandalay, Meiktila District', 20.9454870, 95.5984880, 'APPROVED'),
('Hnaw Kan Station Hospital', 'á€”á€¾á€±á€¬á€€á€”á€ºá€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Mahlaing', 'Mandalay, Meiktila District', 21.2484900, 95.7025290, 'APPROVED'),
('Thazi Township Hospital', 'á€žá€¬á€…á€Šá€ºá€™á€¼á€­á€¯á€·á€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Thazi', 'Mandalay, Meiktila District', 20.8510080, 96.0472900, 'APPROVED'),
('Yin Mar Pin Station Hospital', 'á€šá€„á€ºá€¸á€™á€¬á€•á€„á€ºá€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Thazi', 'Mandalay, Meiktila District', 20.7579020, 96.3140360, 'APPROVED'),
('Nyaung Yan Station Hospital', 'á€Šá€±á€¬á€„á€ºá€›á€™á€ºá€¸á€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Thazi', 'Mandalay, Meiktila District', 20.7541510, 96.0523370, 'APPROVED'),
('Han Zar Station Hospital', 'á€Ÿá€¶á€‡á€¬á€¸á€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Thazi', 'Mandalay, Meiktila District', 21.0009290, 96.0347370, 'APPROVED'),
('Wundwin Township Hospital', 'á€á€™á€ºá€¸á€á€½á€„á€ºá€¸á€™á€¼á€­á€¯á€·á€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Wundwin', 'Mandalay, Meiktila District', 21.0941840, 96.0334010, 'APPROVED'),
('Pin Ta Le Station Hospital', 'á€•á€„á€ºá€¸á€á€œá€²á€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Wundwin', 'Mandalay, Meiktila District', 21.1726330, 95.8483870, 'APPROVED'),
('Nay Pu Kone Station Hospital', 'á€”á€±á€•á€°á€€á€¯á€”á€ºá€¸á€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Wundwin', 'Mandalay, Meiktila District', 21.1944160, 95.9404200, 'APPROVED'),
('Nyaung Oke Hpee Station Hospital', 'á€Šá€±á€¬á€„á€ºá€¡á€¯á€•á€ºá€–á€®á€¸á€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Wundwin', 'Mandalay, Meiktila District', 21.1162240, 96.0948420, 'APPROVED'),
('Insein General Hsoptial', 'á€¡á€„á€ºá€¸á€…á€­á€”á€ºá€¡á€‘á€½á€±á€‘á€½á€±á€›á€±á€¬á€‚á€«á€€á€¯á€†á€±á€¸á€›á€¯á€¶á€€á€¼á€®á€¸', 'Insein', 'Yangon, Yangon (North) District', 16.8920190, 96.1051130, 'APPROVED'),
('Aung San Tuberculosis Hospital', 'á€¡á€±á€¬á€„á€ºá€†á€”á€ºá€¸á€á€®á€˜á€®á€›á€±á€¬á€‚á€«á€€á€¯á€†á€±á€¸á€›á€¯á€¶', 'Insein', 'Yangon, Yangon (North) District', 16.9139100, 96.1029290, 'APPROVED'),
('Railway Hospital', 'á€™á€®á€¸á€›á€‘á€¬á€¸á€†á€±á€¸á€›á€¯á€¶', 'Insein', 'Yangon, Yangon (North) District', 16.8863470, 96.1038330, 'APPROVED'),
('Prison Hospital', 'á€¡á€€á€»á€‰á€ºá€¸á€‘á€±á€¬á€„á€ºá€†á€±á€¸á€›á€¯á€¶', 'Insein', 'Yangon, Yangon (North) District', 16.8918120, 96.0987000, 'APPROVED'),
('Pale Myo Thit Hospital', 'á€•á€¯á€œá€²á€™á€¼á€­á€¯á€·á€žá€…á€ºá€†á€±á€¸á€›á€¯á€¶', 'Mingaladon', 'Yangon, Yangon (North) District', 16.9900000, 96.1434000, 'APPROVED'),
('Hmawbi Township Hospital', 'á€™á€¾á€±á€¬á€ºá€˜á€®á€™á€¼á€­á€¯á€·á€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Hmawbi', 'Yangon, Yangon (North) District', 17.0973900, 96.0428870, 'APPROVED'),
('War Net Chaung Station Hospital', 'á€á€«á€¸á€”á€€á€ºá€á€»á€±á€¬á€„á€ºá€¸á€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Hmawbi', 'Yangon, Yangon (North) District', 17.1686220, 96.0509020, 'APPROVED'),
('Hpu Gyi Station Hospital', 'á€–á€°á€¸á€€á€¼á€®á€¸á€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Hmawbi', 'Yangon, Yangon (North) District', 17.2446340, 96.0120870, 'APPROVED'),
('Nyaung Hnit Pin Station Hospital', 'á€Šá€±á€¬á€„á€ºá€”á€¾á€…á€ºá€•á€„á€ºá€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Hmawbi', 'Yangon, Yangon (North) District', 17.1087000, 96.1271200, 'APPROVED'),
('Hlegu Township Hospital', 'á€œá€¾á€Šá€ºá€¸á€€á€°á€¸á€™á€¼á€­á€¯á€·á€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Hlegu', 'Yangon, Yangon (North) District', 17.0998970, 96.2251360, 'APPROVED'),
('Dar Pein Station Hospital', 'á€’á€«á€¸á€•á€­á€”á€ºá€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Hlegu', 'Yangon, Yangon (North) District', 17.0302740, 96.3666730, 'APPROVED'),
('Hpaung Gyi (East) Station Hospital', 'á€–á€±á€¬á€„á€ºá€€á€¼á€®á€¸á€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Hlegu', 'Yangon, Yangon (North) District', 17.3286730, 96.1855720, 'APPROVED'),
('Ma Yan Chaung Station Hospital', 'á€™á€›á€™á€ºá€¸á€á€»á€±á€¬á€„á€ºá€¸á€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Hlegu', 'Yangon, Yangon (North) District', 17.3879000, 96.2326800, 'APPROVED'),
('Taikkyi Township Hospital', 'á€á€­á€¯á€€á€ºá€€á€¼á€®á€¸á€™á€¼á€­á€¯á€·á€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Taikkyi', 'Yangon, Yangon (North) District', 17.3165420, 95.9601740, 'APPROVED'),
('Hpoe Khaung Station Hospital', 'á€¡á€­á€¯á€„á€ºá€€á€œá€±á€¬á€„á€ºá€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Taikkyi', 'Yangon, Yangon (North) District', 17.3822510, 95.8107690, 'APPROVED'),
('Oke Kan Station Hospital', 'á€¥á€€á€¹á€€á€¶á€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Taikkyi', 'Yangon, Yangon (North) District', 17.4887000, 95.8474520, 'APPROVED'),
('Taw La Ti Station Hospital', 'á€á€±á€¬á€ºá€œá€á€®á€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Taikkyi', 'Yangon, Yangon (North) District', 17.2985530, 95.8339870, 'APPROVED'),
('Ah Phyauk Station Hospital', 'á€¡á€–á€»á€±á€¬á€€á€ºá€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Taikkyi', 'Yangon, Yangon (North) District', 17.3816960, 95.6913560, 'APPROVED'),
('Htantabin Township Hospital', 'á€‘á€”á€ºá€¸á€á€•á€„á€ºá€™á€¼á€­á€¯á€·á€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Htantabin', 'Yangon, Yangon (North) District', 17.0136470, 95.9879820, 'APPROVED'),
('Ne Tha Mein Station Hospital', 'á€”á€¾á€²á€žá€™á€­á€”á€ºá€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Htantabin', 'Yangon, Yangon (North) District', 17.0243060, 95.8226150, 'APPROVED'),
('Hle Seik Station Hospital', 'á€œá€¾á€Šá€ºá€¸á€†á€­á€•á€ºá€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Htantabin', 'Yangon, Yangon (North) District', 17.2418320, 95.8777900, 'APPROVED'),
('Baw Lel Station Hospital', 'á€˜á€±á€¬á€œá€Šá€ºá€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Htantabin', 'Yangon, Yangon (North) District', 17.1688220, 95.7875660, 'APPROVED'),
('Tet Thit Station Hospital', 'á€á€€á€ºá€žá€…á€ºá€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Htantabin', 'Yangon, Yangon (North) District', 16.8796670, 95.9820300, 'APPROVED'),
('Ah Lein Lel Station Hospital', 'á€¡á€œá€­á€”á€ºá€œá€Šá€ºá€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Htantabin', 'Yangon, Yangon (North) District', 17.1112430, 95.9245200, 'APPROVED'),
('Shwepyithar Township Hospital', 'á€›á€½á€¾á€±á€•á€¼á€Šá€ºá€žá€¬á€™á€¼á€­á€¯á€·á€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Shwepyithar', 'Yangon, Yangon (North) District', 16.9698770, 96.0777960, 'APPROVED'),
('Hlaingtharyar Township Hospital', 'á€œá€¾á€­á€¯á€„á€ºá€žá€¬á€šá€¬á€™á€¼á€­á€¯á€·á€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Haling Tharyar', 'Yangon,  District', 16.8751740, 96.0641310, 'APPROVED'),
('Rakhine Chaung Station Hospital', 'á€›á€á€­á€¯á€„á€ºá€á€»á€±á€¬á€„á€ºá€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Dala', 'Yangon, Yangon (South) District', 16.6609250, 96.1785340, 'APPROVED'),
('Shwe Lin Ban Industrial Zone Station Hospital', 'á€›á€½á€¾á€±á€œá€„á€ºá€•á€”á€ºá€¸á€…á€€á€ºá€™á€¾á€¯á€‡á€¯á€”á€ºá€†á€±á€¸á€›á€¯á€¶', 'Hlaingtharyar', 'Yangon, NA District', 16.9060300, 96.0619580, 'APPROVED'),
('Thingyangyun General Hospital', 'á€žá€„á€ºá€¹á€ƒá€”á€ºá€¸á€€á€»á€½á€”á€ºá€¸á€…á€¶á€•á€¼á€¡á€‘á€½á€±á€‘á€½á€±á€›á€±á€¬á€‚á€«á€€á€¯á€†á€±á€¸á€›á€¯á€¶á€€á€¼á€®á€¸', 'Thingangyun', 'Yangon, Yangon (East) District', 16.8343800, 96.1905380, 'APPROVED'),
('Yankin Children Specialist Hospital', 'á€€á€œá€±á€¸á€›á€±á€¬á€‚á€«á€¡á€‘á€°á€¸á€€á€¯á€†á€±á€¸á€›á€¯á€¶á€€á€¼á€®á€¸', 'Yankin', 'Yangon, Yangon (East) District', 16.8352730, 96.1600750, 'APPROVED'),
('South Okkalapa Women and Children', 'á€¡á€™á€»á€­á€¯á€¸á€žá€™á€®á€¸á€”á€¾á€„á€·á€ºá€€á€œá€±á€¸á€†á€±á€¸á€›á€¯á€¶', 'South Okkalapa', 'Yangon, Yangon (East) District', 16.8454920, 96.1867010, 'APPROVED'),
('North Okkalapa Teaching and General Hospital', 'â€‹á€™á€¼á€±á€¬á€€á€ºá€¥á€€á€¹á€€á€œá€¬á€• á€žá€„á€ºá€€á€¼á€¬á€¸á€›á€±á€¸á€”á€¾á€„á€·á€ºá€¡á€‘á€½á€±á€‘á€½á€±á€›á€±á€¬á€‚á€«á€€á€¯á€†á€±á€¸á€›á€¯á€¶á€€á€¼á€®á€¸', 'North Okkalapa', 'Yangon, Yangon (East) District', 16.9007920, 96.1580630, 'APPROVED'),
('Way Bar Gi Specialist Hospital', 'á€¡á€‘á€°á€¸á€€á€¯á€†á€±á€¸á€›á€¯á€¶(á€á€±á€˜á€¬á€‚á€®)', 'North Okkalapa', 'Yangon, Yangon (East) District', 16.9205520, 96.1565320, 'APPROVED'),
('Thar Kay Ta Special Hospital', 'á€žá€¬á€€á€±á€á€¡á€‘á€°á€¸á€€á€¯á€†á€±á€¸á€›á€¯á€¶', 'Thaketa', 'Yangon, Yangon (East) District', 16.8058170, 96.2171190, 'APPROVED'),
('Ear, Nose and Throat Hospital', 'á€”á€¬á€¸áŠá€”á€¾á€¬á€á€±á€«á€„á€ºá€¸áŠá€œá€Šá€ºá€á€»á€±á€¬á€„á€ºá€¸á€›á€±á€¬á€‚á€«á€¡á€‘á€°á€¸á€€á€¯á€†á€±á€¸á€›á€¯á€¶á€€á€¼á€®á€¸', 'Tamwe', 'Yangon, Yangon (East) District', 16.8079610, 96.1725020, 'APPROVED'),
('Eye Speacial Hospital', 'á€™á€»á€€á€ºá€…á€­á€›á€±á€¬á€‚á€«á€€á€¯á€†á€±á€¸á€›á€¯á€¶', 'Tamwe', 'Yangon, Yangon (East) District', 16.7997970, 96.1706050, 'APPROVED'),
('Botahtaung General Hospital', 'á€¡á€›á€¾á€±á€·á€•á€­á€¯á€„á€ºá€¸á€•á€¼á€Šá€ºá€žá€°á€·á€†á€±á€¸á€›á€¯á€¶', 'Botahtaung', 'Yangon, Yangon (East) District', 16.7717190, 96.1741160, 'APPROVED'),
('Dagon Myothit (South) Township Hospital', 'á€’á€‚á€¯á€¶á€™á€¼á€­á€¯á€·á€žá€…á€º(á€á€±á€¬á€„á€º)á€™á€¼á€­á€¯á€·á€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Dagon Myothit (South)', 'Yangon, Yangon (East) District', 16.8510880, 96.2208620, 'APPROVED'),
('Station Hospital', 'á€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Dagon Myothit (South)', 'Yangon, Yangon (East) District', 16.8513220, 96.2204030, 'APPROVED'),
('Lay Daunt Kan Station Hospital', 'á€œá€±á€¸á€‘á€±á€¬á€„á€·á€ºá€€á€”á€ºá€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Dagon Myothit (South)', 'Yangon, Yangon (East) District', 16.9608020, 96.3026070, 'APPROVED'),
('Dagon Myothit (North) Township Hospital', 'á€’á€‚á€¯á€¶á€™á€¼á€­á€¯á€·á€žá€…á€º(á€™á€¼á€±á€¬á€€á€º)á€™á€¼á€­á€¯á€·á€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Dagon Myothit (North)', 'Yangon, Yangon (East) District', 16.8914560, 96.1990360, 'APPROVED'),
('Dagon University Hospital', 'á€’á€‚á€¯á€¶á€á€€á€¹á€€á€žá€­á€¯á€œá€ºá€†á€±á€¸á€›á€¯á€¶', 'Dagon Myothit (East)', 'Yangon, Yangon (East) District', 16.9118100, 96.2102800, 'APPROVED'),
('Psychiatric Hospital', 'á€…á€­á€á€ºá€€á€»á€”á€ºá€¸á€™á€¬á€›á€±á€¸á€†á€±á€¸á€›á€¯á€¶á€€á€¼á€®á€¸', 'Dagon Myothit (East)', 'Yangon, Yangon (East) District', 16.9624410, 96.2628190, 'APPROVED'),
('Dagon Myothit (East) Township Hospital', 'á€’á€‚á€¯á€¶á€™á€¼á€­á€¯á€·á€žá€…á€º(á€¡á€›á€¾á€±á€·)á€™á€¼á€­á€¯á€·á€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Dagon Myothit (East)', 'Yangon, Yangon (East) District', 16.9178210, 96.2318660, 'APPROVED'),
('Dagon Myothit (Seikkan) Township Hospital', 'á€’á€‚á€¯á€¶á€™á€¼á€­á€¯á€·á€žá€…á€º(á€†á€­á€•á€ºá€€á€™á€ºá€¸)á€™á€¼á€­á€¯á€·á€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Dagon Myothit (Seikkan)', 'Yangon, Yangon (East) District', 16.8584350, 96.2809000, 'APPROVED'),
('Thanlyin General Hospital', 'á€žá€”á€ºá€œá€»á€„á€ºá€•á€¼á€Šá€ºá€žá€°á€·á€†á€±á€¸á€›á€¯á€¶', 'Thanlyin', 'Yangon, Yangon (South) District', 16.7597270, 96.2525750, 'APPROVED'),
('Day Zat Station Hospital', 'á€’á€±á€¸á€‡á€€á€ºá€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Thanlyin', 'Yangon, Yangon (South) District', 16.9061570, 96.3468660, 'APPROVED'),
('Kyauktan Township Hospital', 'á€€á€»á€±á€¬á€€á€ºá€á€”á€ºá€¸á€™á€¼á€­á€¯á€·á€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Kyauktan', 'Yangon, Yangon (South) District', 16.6368010, 96.3269090, 'APPROVED'),
('Tadar Ywar Station Hospital', 'á€á€¶á€á€¬á€¸á€›á€½á€¬á€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Kyauktan', 'Yangon, Yangon (South) District', 16.6530680, 96.5412550, 'APPROVED'),
('Mee Pya Station Hospital', 'á€™á€®á€¸á€•á€¼á€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Kyauktan', 'Yangon, Yangon (South) District', 16.5470380, 96.3277360, 'APPROVED'),
('Min Ga Lun Station Hospital', 'á€™á€„á€ºá€¹á€‚á€œá€½á€”á€ºá€¸á€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Kyauktan', 'Yangon, Yangon (South) District', 16.5824130, 96.4623790, 'APPROVED'),
('Ka Mar Ka Loke Station Hospital', 'á€€á€™á€¬á€€á€œá€¯á€•á€ºá€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Kyauktan', 'Yangon, Yangon (South) District', 16.5502430, 96.4190530, 'APPROVED'),
('Kyon Kan Station Hospital', 'á€€á€»á€¯á€¶á€€á€”á€ºá€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Kyauktan', 'Yangon, Yangon (South) District', 16.6635440, 96.4437220, 'APPROVED'),
('Thongwa Township Hospital', 'á€žá€¯á€¶á€¸á€á€½á€™á€¼á€­á€¯á€·á€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Thongwa', 'Yangon, Yangon (South) District', 16.7601200, 96.5232420, 'APPROVED'),
('Nyaung Lan Kone Station Hospital', 'á€Šá€±á€¬á€„á€ºá€œá€”á€ºá€¸á€€á€¯á€”á€ºá€¸á€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Thongwa', 'Yangon, Yangon (South) District', 16.7484520, 96.6822710, 'APPROVED'),
('Kayan Township Hospital', 'á€á€›á€™á€ºá€¸á€™á€¼á€­á€¯á€·á€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Kayan', 'Yangon, Yangon (South) District', 16.9035280, 96.5586100, 'APPROVED'),
('Yae Kyaw Station Hospital', 'á€›á€±á€€á€»á€±á€¬á€º(á€€á€™á€¬á€™á€á€º)á€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Kayan', 'Yangon, Yangon (South) District', 16.8701000, 96.7676000, 'APPROVED'),
('Kyi Ni Chaung Station Hospital', 'á€€á€»á€®á€”á€®á€á€»á€±á€¬á€„á€ºá€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Kayan', 'Yangon, Yangon (South) District', 16.9404130, 96.6726480, 'APPROVED'),
('Pein Kan Station Hospital', 'á€•á€­á€”á€ºá€¸á€€á€”á€ºá€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Kayan', 'Yangon, Yangon (South) District', 16.8728530, 96.4515610, 'APPROVED'),
('Twantay Township Hospital', 'á€á€½á€¶á€á€±á€¸á€™á€¼á€­á€¯á€·á€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Twantay', 'Yangon, Yangon (South) District', 16.7059780, 95.9333290, 'APPROVED'),
('Khat Hti Ya Station Hospital', 'á€á€á€¹á€á€­á€šá€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Twantay', 'Yangon, Yangon (South) District', 16.8786000, 95.8466350, 'APPROVED'),
('Kayin Chaung Station Hospital', 'á€€á€›á€„á€ºá€á€»á€±á€¬á€„á€ºá€¸á€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Twantay', 'Yangon, Yangon (South) District', 16.6451200, 95.8358450, 'APPROVED'),
('Kawhmu Township Hospital', 'á€€á€±á€¬á€·á€™á€¾á€°á€¸á€™á€¼á€­á€¯á€·á€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Kawhmu', 'Yangon, Yangon (South) District', 16.5555490, 96.0616480, 'APPROVED'),
('Kyaik Htaw Station Hospital', 'á€€á€»á€­á€¯á€€á€ºá€‘á€±á€¬á€ºá€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Kawhmu', 'Yangon, Yangon (South) District', 16.5179610, 95.8602190, 'APPROVED'),
('War Ba Lauk Thauk Station Hospital', 'á€á€«á€¸á€˜á€œá€±á€¬á€€á€ºá€žá€±á€¬á€€á€ºá€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Kawhmu', 'Yangon, Yangon (South) District', 16.5161360, 96.1683390, 'APPROVED'),
('Kungyangon Township Hospital', 'á€€á€½á€™á€ºá€¸á€á€¼á€¶á€€á€¯á€”á€ºá€¸á€™á€¼á€­á€¯á€·á€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Kungyangon', 'Yangon, Yangon (South) District', 16.4380620, 96.0076380, 'APPROVED'),
('Let Khoke Kone Station Hospital', 'á€œá€€á€ºá€á€¯á€•á€ºá€€á€¯á€”á€ºá€¸á€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Kungyangon', 'Yangon, Yangon (South) District', 16.3409550, 96.1608830, 'APPROVED'),
('Da Yei Lu Station Hospital', 'á€’á€›á€šá€ºá€œá€°á€¸á€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Kungyangon', 'Yangon, Yangon (South) District', 16.4428190, 96.1887590, 'APPROVED'),
('Dala Township Hospital', 'á€’á€œá€™á€¼á€­á€¯á€·á€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Dala', 'Yangon, Yangon (South) District', 16.7583150, 96.1553700, 'APPROVED'),
('Pyawbwe Gyi Station Hospital', 'á€•á€»á€±á€¬á€ºá€˜á€½á€šá€ºá€€á€¼á€®á€¸á€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Dala', 'Yangon, Yangon (South) District', 16.6783130, 96.1419260, 'APPROVED'),
('Seikgyikanaungto Township Hospital', 'á€†á€­á€•á€ºá€€á€¼á€®á€¸á€á€”á€±á€¬á€„á€ºá€á€­á€¯á€™á€¼á€­á€¯á€·á€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Seikgyikanaungto', 'Yangon, Yangon (South) District', 16.7551370, 96.1099190, 'APPROVED'),
('Cocokyun Township Hospital', 'á€€á€­á€¯á€€á€­á€¯á€¸á€€á€»á€½á€”á€ºá€¸á€™á€¼á€­á€¯á€·á€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Cocokyun', 'Yangon, Yangon (South) District', 14.1375130, 93.3690670, 'APPROVED'),
('New Yangon General Hospital', 'á€›á€”á€ºá€€á€¯á€”á€ºá€¡á€‘á€½á€±á€‘á€½á€±á€›á€±á€¬á€‚á€«á€€á€¯á€†á€±á€¸á€›á€¯á€¶á€žá€…á€ºá€€á€¼á€®á€¸', 'Lanmadaw', 'Yangon, Yangon (West) District', 16.7815320, 96.1452540, 'APPROVED'),
('Latha General Hospital', 'á€›á€”á€ºá€€á€¯á€”á€ºá€•á€¼á€Šá€ºá€žá€°á€·á€†á€±á€¸á€›á€¯á€¶á€€á€¼á€®á€¸', 'Latha', 'Yangon, Yangon (West) District', 16.7791410, 96.1489830, 'APPROVED'),
('Central Women Hospital', 'á€—á€Ÿá€­á€¯á€¡á€™á€»á€­á€¯á€¸á€žá€™á€®á€¸á€†á€±á€¸á€›á€¯á€¶á€€á€¼á€®á€¸', 'Lanmadaw', 'Yangon, Yangon (West) District', 16.7852570, 96.1354570, 'APPROVED'),
('(500) Bedded General Hospital', 'á€€á€¯á€á€„á€ºá…á€á€á€¡á€‘á€½á€±á€‘á€½á€±á€›á€±á€¬á€‚á€«á€€á€¯á€†á€±á€¸á€›á€¯á€¶á€žá€…á€ºá€€á€¼á€®á€¸', 'Lanmadaw', 'Yangon, Yangon (West) District', 16.7814080, 96.1452130, 'APPROVED'),
('Kyeemyindaing General Hospital', 'á€¡á€”á€±á€¬á€€á€ºá€•á€­á€¯á€„á€ºá€¸á€•á€¼á€Šá€ºá€žá€°á€·á€†á€±á€¸á€›á€¯á€¶', 'Kyeemyindaing', 'Yangon, Yangon (West) District', 16.7959310, 96.1255480, 'APPROVED'),
('Orthopedic Hospital', 'á€¡á€›á€­á€¯á€¸á€›á€±á€¬á€‚á€«á€€á€¯á€†á€±á€¸á€›á€¯á€¶á€€á€¼á€®á€¸', 'Kyeemyindaing', 'Yangon, Yangon (West) District', 16.8191680, 96.1224190, 'APPROVED'),
('Set San Station Hospital', 'á€…á€€á€ºá€†á€”á€ºá€¸á€á€­á€¯á€€á€ºá€”á€šá€ºá€†á€±á€¸á€›á€¯á€¶', 'Kyeemyindaing', 'Yangon, Yangon (West) District', 16.8118560, 96.1117140, 'APPROVED'),
('Yangon University Hospital', 'á€›á€”á€ºá€€á€¯á€”á€ºá€á€€á€¹á€€á€žá€­á€¯á€œá€ºá€†á€±á€¸á€›á€¯á€¶', 'Kamaryut', 'Yangon, Yangon (West) District', 16.8258250, 96.1344430, 'APPROVED'),
('National Rehabilitation Hospital', 'á€¡á€™á€»á€­á€¯á€¸á€žá€¬á€¸á€•á€¼á€”á€ºá€œá€Šá€ºá€žá€”á€ºá€…á€½á€™á€ºá€¸á€›á€±á€¸á€†á€±á€¸á€›á€¯á€¶', 'Mayangone', 'Yangon, Yangon (West) District', 16.8656810, 96.1317590, 'APPROVED'),
('Kabar Aye Monk hospitals', 'á€€á€™á€¹á€˜á€¬á€·á€¡á€±á€¸á€žá€¶á€ƒá€¬á€·á€†á€±á€¸á€›á€¯á€¶', 'Mayangone', 'Yangon, Yangon (West) District', 16.8579910, 96.1502530, 'APPROVED'),
('Children Specialist Hospital', 'á€€á€œá€±á€¸á€›á€±á€¬á€‚á€«á€¡á€‘á€°á€¸á€€á€¯á€†á€±á€¸á€›á€¯á€¶á€€á€¼á€®á€¸', 'Dagon', 'Yangon, Yangon (West) District', 16.7883090, 96.1360530, 'APPROVED'),
('Bahan Women Hospital', 'á€—á€Ÿá€”á€ºá€¸á€¡á€™á€»á€­á€¯á€¸á€žá€™á€®á€¸á€†á€±á€¸á€›á€¯á€¶', 'Bahan', 'Yangon, Yangon (West) District', 16.8064970, 96.1646810, 'APPROVED'),
('Kandawnadi Hospital', 'á€€á€”á€ºá€á€±á€¬á€ºá€”á€’á€®á€†á€±á€¸á€›á€¯á€¶', 'Chanmyathazi', 'Mandalay, Mandalay District', 21.9456000, 96.1122810, 'APPROVED');
